# Flutter localization generation for AS-FrooshYar.
arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
preferred-supported-locales:
- "fa"
- "en"
- "zh"
use-deferred-loading: true
untranslated-messages-file: docs/untranslated.json
