name: possystem
description: AS-FrooshYar - Persian offline-first sales, inventory and cashier application by AS Team Group
publish_to: "none"
homepage: https://github.com/waxew/AS-FrooshYar
repository: https://github.com/waxew/AS-FrooshYar
version: 1.0.0+1

environment:
  flutter: ">=3.41.0 <3.42.0"
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core helper
  go_router: ^16.2.5
  provider: ^6.1.5
  intl: ^0.20.2
  collection: ^1.19.1
  firebase_core: ^3.15.2
  firebase_analytics: ^11.6.0
  firebase_auth: ^5.7.0
  firebase_crashlytics: ^4.3.10
  firebase_in_app_messaging: ^0.8.1+10
  firebase_performance: ^0.10.1+10

  # services
  sqflite: ^2.4.2
  sembast: ^3.8.5
  shared_preferences: ^2.5.3
  http: ^1.5.0
  packages:
    git:
      url: https://github.com/evan361425/flutter-pos-packages-mock
      ref: master
  flutter_blue_plus:
    git:
      url: https://github.com/evan361425/flutter_blue_plus
      ref: uint8
      path: packages/flutter_blue_plus

  # google services
  googleapis: ^14.0.0
  google_sign_in: ^6.3.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

  # components
  table_calendar: ^3.2.0
  syncfusion_flutter_charts: ^30.2.6+1
  spotlight_ant: ^1.4.5
  editor_ant: ^1.3.10

  # image
  image: ^4.5.4
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  image_cropper: ^9.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1

  # Make it easy to test
  file: ^7.0.1

  # tools
  uuid: ^4.5.1
  wakelock_plus: ^1.3.2
  characters: ^1.4.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  package_info_plus: ^8.3.0
  visibility_detector: ^0.4.0+2
  cupertino_icons: ^1.0.8
  excel:
    git:
      url: https://github.com/evan361425/excel
      ref: patch-1

dependency_overrides:
  flutter_blue_plus:
    git:
      url: https://github.com/evan361425/flutter_blue_plus
      ref: uint8
      path: packages/flutter_blue_plus
  flutter_blue_plus_platform_interface:
    git:
      url: https://github.com/evan361425/flutter_blue_plus
      ref: uint8
      path: packages/flutter_blue_plus_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code style
  flutter_lints: ^5.0.0
  prefer_shorthands: ^0.4.7

  # mock object
  build_runner: ^2.5.4
  mockito: ^5.4.6
  sqflite_common: ^2.5.5
  sqflite_common_ffi: ^2.3.6

  arb_glue: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/food_placeholder.png
  - assets/google_sheet_icon.svg
  - assets/feature_request_please.gif
  - assets/google_signin_button.svg
  - assets/excel_icon.svg

flutter_native_splash:
  color: "#5c98ff"
  fullscreen: true
  image: assets/logo.png

arb_glue:
  source: assets/l10n
  destination: lib/l10n
  author: AS Team Group
  fileTemplate: 'app_{lang}.arb'
  base: en
  lastModified: false
  verbose: true
